// Copyright (c) Eclypses, Inc.
// 
// All rights reserved.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// WARNING: This file is automatically generated. Do not edit.

package com.eclypses.mte;

import java.util.Map;
import java.util.HashMap;

// Cipher algorithms.
public enum MteCiphers
{
  // None. An external cipher must be provided instead.
  mte_ciphers_none,

  // AES-128-CTR.
  mte_ciphers_aes128_ctr,

  // AES-192-CTR.
  mte_ciphers_aes192_ctr,

  // AES-256-CTR.
  mte_ciphers_aes256_ctr;

  // Enum <-> Integer conversion.
  public int getValue() { return ordinal(); }
  public static MteCiphers valueOf(int i) { return map.get(i); }
  private static final Map<Integer, MteCiphers> map =
    new HashMap<>();
  static
  {
    for (MteCiphers e : MteCiphers.values())
    {
      map.put(e.getValue(), e);
    }
  }

} 



